#!/usr/bin/env python3
"""
lift_dinopark.py - lift the sprite-decode functions to C (recomp16 model).

Targets the self-contained DPCM decode group found in Phase 3:
    FUN_1000_0e50  scanline DPCM decoder   (calls the three helpers)
    FUN_1000_0f2e  8-bit-group delta expand
    FUN_1000_103b  4-bit-group delta expand
    FUN_1000_10de  2-bit-group delta expand

We work in *image-offset* space: the load image (file from hdr_size=0x4800) sits
at linear 0, so a Ghidra `1000:xxxx` address = file_off - 0x4800. Near calls
between the four resolve in that space via known_funcs.

Output: src/recomp/gen/dino_decode.c + dino_decode.h (forward decls).
"""
import os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _pcrecomp_home():
    """Where the pcrecomp toolkit lives.

    PCRECOMP_HOME if it is set, otherwise a sibling checkout next to this one --
    which is how the recomp projects are laid out. Never a hardcoded absolute
    path: that is one person's drive letter, and it belongs in an environment
    variable rather than in a public repository.
    """
    env = os.environ.get("PCRECOMP_HOME")
    cands = [env] if env else []
    cands += [os.path.join(os.path.dirname(ROOT), "tools"),
              os.path.join(ROOT, "..", "pcrecomp")]
    for c in cands:
        if c and os.path.isdir(os.path.join(c, "tools", "disasm")):
            return os.path.abspath(c)
    raise SystemExit(
        "cannot find the pcrecomp toolkit.%s"
        "Set PCRECOMP_HOME to your checkout of%s"
        "  https://github.com/sp00nznet/pcrecomp%s"
        "(looked in: %s)" % (chr(10), chr(10), chr(10), ", ".join(str(c) for c in cands)))


TOOLS = _pcrecomp_home()
sys.path.insert(0, os.path.join(TOOLS, "tools", "disasm"))
sys.path.insert(0, os.path.join(TOOLS, "tools", "lift"))
from decode16 import Decoder          # noqa: E402
from lift16 import Lifter             # noqa: E402

HDR = 0x4800
EXE = os.path.join(ROOT, "original", "DINOPARK.EXE")
OUT = os.path.join(ROOT, "src", "recomp", "gen")

# (name, file_start, file_end)  -- from work/functions.json
FUNCS = [
    ("fn_0E50", 0x5650, 0x572E),   # DPCM scanline decoder (.ABT / some assets)
    ("fn_0F2E", 0x572E, 0x583B),   # DPCM helper (8/byte)
    ("fn_103B", 0x583B, 0x58DE),   # DPCM helper (4/byte)
    ("fn_10DE", 0x58DE, 0x5946),   # DPCM helper (2/byte)
    ("fn_1907", 0xD92E, 0xDA0E),   # RLE / raw-copy blitter (.PIC full-screen art)
    # The planar actor blitter FUN_191d_08fb lifts cleanly too — add
    #   ("fn_E2CB", 0xE2CB, 0xE48E),
    # to regenerate it into work/. Reading its lifted C gave the exact .ACT
    # control-stream semantics that tools/decode_act.py implements (the inner
    # plotter's computed `jmp bx` + VGA planar writes aren't needed for the
    # logical image — the de-interleave just reconstructs x-order).
]


def main():
    data = open(EXE, "rb").read()
    os.makedirs(OUT, exist_ok=True)

    # image-offset = file - HDR ; known_funcs keyed in that space
    known = {fs - HDR: name for name, fs, fe in FUNCS}

    bodies, all_calls = [], set()
    for name, fs, fe in FUNCS:
        img_off = fs - HDR
        insns = Decoder(data[fs:fe], base_offset=img_off).decode_all()
        lifter = Lifter(hdr_size=HDR, known_funcs=known)
        # decode functions are __cdecl16far (RETF)
        body = lifter.lift_function(name, insns, img_off, is_far=True)
        bodies.append(body)
        all_calls |= lifter.func_calls

    names = [n for n, _, _ in FUNCS]
    # Calls to functions we didn't lift (e.g. the planar inner plotter
    # res_009DC7 = FUN_191d_0bf7, whose computed `jmp bx` doesn't auto-lift) get
    # an empty stub so the unit still links. They aren't on the harness paths.
    stubs = sorted(c for c in all_calls if c not in names)

    with open(os.path.join(OUT, "dino_decode.h"), "w") as f:
        f.write("#ifndef DINO_DECODE_H\n#define DINO_DECODE_H\n")
        f.write('#include "../cpu.h"\n\n')
        for n in names:
            f.write(f"void {n}(CPU *cpu);\n")
        f.write("\n#endif\n")

    # Expose the decoder's end-of-decode si/di (the harness needs the consumed/
    # produced counts; the function restores si/di in its epilogue). Capture at
    # the epilogue label, before the pops.
    bodies = [b.replace("L_fn_0E50_0000D3:;",
                        "L_fn_0E50_0000D3:; g_end_si = cpu->si; g_end_di = cpu->di;", 1)
              for b in bodies]

    with open(os.path.join(OUT, "dino_decode.c"), "w") as f:
        f.write("/* Auto-generated by tools/lift_dinopark.py - DO NOT EDIT. */\n")
        f.write('#include "dino_decode.h"\n')
        f.write("#include <stdlib.h>\n")
        f.write("unsigned g_end_si, g_end_di;  /* decode end positions (harness) */\n")
        # Unreachable tail-dispatch stub: the analyzer's end bound can overrun the
        # real RET by a few bytes, so the lifter emits a fallthrough we never hit.
        f.write("void recomp_dispatch(CPU *cpu, unsigned seg, unsigned off) {\n")
        f.write('    (void)cpu; (void)seg; (void)off;\n')
        f.write('    /* should be unreachable for these leaf decoders */\n}\n')
        for s in stubs:
            f.write(f"void {s}(CPU *cpu) {{ (void)cpu; }}  /* unlifted callee stub */\n")
        f.write("\n")
        f.write("\n\n".join(bodies))
        f.write("\n")

    print(f"Lifted {len(FUNCS)} functions -> {OUT}/dino_decode.c")
    unresolved = all_calls - set(names)
    if unresolved:
        print("  WARNING unresolved calls:", unresolved)
    else:
        print("  all near calls resolved within the group")


if __name__ == "__main__":
    main()
